from pathlib import Path

files = [
    Path('src/app/page.tsx'),
    Path('src/app/matches/page.tsx'),
    Path('src/app/matches/[id]/page.tsx'),
    Path('src/app/booking/cart/page.tsx'),
    Path('src/app/booking/checkout/page.tsx'),
    Path('src/app/auth/login/page.tsx'),
    Path('src/components/ui/Navbar.tsx'),
    Path('src/components/ui/Footer.tsx'),
]

repls = {
    'FIFA World Cup 2026 · Plateforme Officielle': 'FIFA World Cup 2026 · Official Platform',
    'Billets officiels': 'Official tickets',
    'Réservation simple': 'Simple booking',
    'Assistance 24h/24': '24/7 support',
    'Villes hôtes': 'Host cities',
    'Billets disponibles': 'Tickets available',
    'Match phare': 'Featured match',
    'Disponible': 'Available',
    'Complet': 'Sold out',
    'À partir de': 'From',
    'Réserver': 'Book',
    'Réserver maintenant': 'Book now',
    'Phases finales': 'Final phase',
    'Phase à élimination directe': 'Knockout phase',
    'Rencontres décisives': 'Decisive matches',
    'Grande demi-finale': 'Major semifinal',
    'Bataille pour le bronze': 'Bronze medal battle',
    'Événement principal': 'Main event',
    'Phase finale': 'Final phase',
    'Types de billets': 'Ticket types',
    'Choisissez votre expérience': 'Choose your experience',
    'Témoignages': 'Testimonials',
    'Ce que disent nos clients': 'What our clients say',
    'Questions fréquentes': 'Frequently asked questions',
    'Disponibilité limitée': 'Limited availability',
    'Ne manquez aucun': 'Don’t miss any',
    'Réservez vos billets dès aujourd’hui. Plus de 5 millions de supporters font confiance à notre plateforme.': 'Book your tickets today. More than 5 million fans trust our platform.',
    'Pourquoi nous choisir': 'Why choose us',
    'Une plateforme conçue pour vous': 'A platform designed for you',
    'Réservation simple via WhatsApp, sans paiement en ligne, avec billets PDF instantanés.': 'Simple WhatsApp booking, no online payment, and instant PDF tickets.',
    'Réservez vos billets officiels et vivez une expérience exceptionnelle au cœur du plus grand événement sportif mondial.': 'Book your official tickets and enjoy an exceptional experience at the heart of the biggest sporting event in the world.',
    'Tous les Matchs': 'All Matches',
    'matchs disponibles': 'matches available',
    'Filtrer': 'Filter',
    'Effacer': 'Clear',
    'Équipe, stade…': 'Team, stadium…',
    'Toutes les phases': 'All stages',
    'Aucun match trouvé': 'No matches found',
    'Essayez d’ajuster vos filtres.': 'Try adjusting your filters.',
    'Précédent': 'Previous',
    'Suivant': 'Next',
    'Accueil': 'Home',
    'Matchs': 'Matches',
    'Billets': 'Tickets',
    'Stades': 'Stadiums',
    'Contact': 'Contact',
    'Mon tableau de bord': 'My dashboard',
    'Déconnexion': 'Log out',
    'Connexion': 'Login',
    'Inscription': 'Register',
    'Mon compte': 'My account',
    'Créer un compte': 'Create an account',
    'Mot de passe oublié ?': 'Forgot password?',
    'Se souvenir de moi': 'Remember me',
    'Connexion…': 'Logging in…',
    'ou': 'or',
    'Votre email…': 'Your email…',
    'Plateforme officielle de réservation de billets pour la Coupe du Monde FIFA 2026.': 'Official ticket booking platform for the FIFA World Cup 2026.',
    'Tous droits réservés. Partenaire officiel FIFA World Cup 2026.': 'All rights reserved. Official partner of the FIFA World Cup 2026.',
    'Prochains matchs': 'Upcoming matches',
    'Matchs populaires': 'Popular matches',
    'Découvrez les rencontres phares de la Coupe du Monde 2026 avec des cartes modernes, des prix de départ attractifs et un parcours de réservation fluide.': 'Discover the headline matches of the FIFA World Cup 2026 with modern cards, attractive starting prices, and a smooth booking experience.',
    'Faire défiler vers la gauche': 'Scroll left',
    'Faire défiler vers la droite': 'Scroll right',
    'Prix à partir de': 'Price from',
    'Vivez la': 'Experience the',
    'Coupe du Monde': 'World Cup',
    'Billets officiels garantis': 'Guaranteed official tickets',
    'PDF instantané': 'Instant PDF',
    'Réservation via WhatsApp': 'WhatsApp booking',
    'Votre panier est vide': 'Your cart is empty',
    'Parcourez les matchs disponibles et ajoutez des billets pour commencer.': 'Browse available matches and add tickets to get started.',
    'Explorer les matchs': 'Explore matches',
    'Continuer mes achats': 'Continue shopping',
    'Mon panier': 'My cart',
    'Vider le panier': 'Clear cart',
    'Supprimer': 'Remove',
    'Récapitulatif': 'Summary',
    'Réserver via WhatsApp': 'Book via WhatsApp',
    'Aucun paiement en ligne': 'No online payment',
    'Match introuvable.': 'Match not found.',
    'Connectez-vous pour réserver': 'Please log in to book',
    'Places épuisées': 'Sold out',
    'Quantité maximale atteinte': 'Maximum quantity reached',
    'ajouté au panier': 'added to cart',
    'Retour aux matchs': 'Back to matches',
    'Capacité :': 'Capacity:',
    'places': 'seats',
    'Sélectionner vos billets': 'Select your tickets',
    'Ce match a été annulé.': 'This match has been canceled.',
    'Ce match est terminé.': 'This match is finished.',
    'Épuisé': 'Sold out',
    'par billet': 'per ticket',
    'Votre demande est en cours': 'Your request is in progress',
    'Nous avons préparé vos informations de réservation et vous redirigeons vers WhatsApp pour confirmation.': 'We prepared your booking details and are redirecting you to WhatsApp for confirmation.',
    'Réservation assistée': 'Assisted booking',
    'Confirmation par WhatsApp': 'WhatsApp confirmation',
}

for path in files:
    text = path.read_text(encoding='utf-8')
    for old, new in repls.items():
        text = text.replace(old, new)
    path.write_text(text, encoding='utf-8')

print('Updated', len(files), 'files')
